### ISSUE TITLE
Depend on `pyephem` rather than `ephem`?

### ISSUE THREAD

**Issue by pkgw** [conda-forge/aipy-feedstock#3]
Looks like conda-forge has two packages of the pyephem code. Installing on NRAO, `ephem` had a binary linkage problem but `pyephem` worked.

**Comment by pkgw** [comment]
Oh, wait, maybe `pyemphem` is also broken. To be investigated.

**Comment by pkgw** [comment]
Double oh-wait: local configuration problem. Conda-forge still has redundant packages but that's beyond the purview of this package.

**Comment by ocefpaf** [comment]
> Conda-forge still has redundant packages but that's beyond the purview of this package.

Ping @mwcraig any decision on this?

**Comment by mwcraig** [comment]
I think the author of the package prefers `ephem` (see https://github.com/conda-forge/staged-recipes/pull/3495#issuecomment-322460438).

I would prefer that we not immediately delete `pyephem`, though, because I need to update some depends first.

**Comment by ocefpaf** [comment]
> I would prefer that we not immediately delete `pyephem`, though, because I need to update some depends first.

No problem.
