### ISSUE TITLE
CircleCI builds not happening automatically

### ISSUE THREAD

**Issue by pkgw** [conda-forge/aipy-feedstock#8]
If I go to this feedstock's [CircleCI overview page](https://circleci.com/gh/conda-forge/aipy-feedstock/edit), it says that builds aren't happening because "no one is following this project". If I click the "follow project" button, it says "Failed to follow".

I can kick off builds manually but this is obviously not how things are supposed to work. Any idea, @conda-forge/core? Some part of the feedstock setup failed, or something?

**Comment by isuruf** [comment]
@conda-forge-admin, please update circle

**Comment by jakirkham** [comment]
Could you please try readding the recipe through `staged-recipes`? That should update any feedstock content that has gotten messed up.

**Comment by jakirkham** [comment]
Appears CircleCI triggered for the latest commit on `master` after the readd.

**Comment by pkgw** [comment]
Yeah looks like this got fixed.
